### ISSUE TITLE
Generates only two-three unique ULIDs in a same millisecond

### ISSUE THREAD

**Issue by Fauzdar1** [GuepardoApps/kULID#2]
When generating `ULIDs` for a list of items of more than 2-3, it generates same `ULIDs`. Sometimes, it generates only two unique IDs, sometimes three, others are just copy of the last unique ID. 

I use `ULID` to name files before uploading them on server. For example - if I'm uploading 10 items, it names 7-8 of them same which results in no error but only 2-3 files get uploaded as same name file overwrites other. 

I've gone through the Wiki of ULID/spec but nothing is mentioned there to overcome this problem. And I can't find anything related to `MonotoniFactory` in this lib's methods.

Here's how I use it:

```
private fun generateFileName(): String {
return ULID.generate(
     System.currentTimeMillis(),
     byteArrayOf(0x0, 0x1, 0x2, 0x3, 0x4, 0x5, 0x6, 0x7, 0x8, 0x9)
    ) + ".png"
}
```
Check the below image : Out of 14, only two are unique. 01EBTT93BM... and 01EBTT93BN...
![image](https://user-images.githubusercontent.com/62703211/85921772-37468980-b89c-11ea-9d36-177990f0aeff.png)

Any workaround to fix it?

**Edit**: The workaround I've implemented it to pass the list index as well to the method `generateFileName()` and adding it to the generated Id as `+ "-${index+1}.png"`.

**Comment by wakino** [comment]
You should use ULID.random() simply. Or put random data as 2nd parameter of UILD.generate().
